"use client";
import {api} from '@/lib/client-api';
import {AI_MODEL_IDS,AI_MODELS,DEFAULT_AI_MODEL,type AIModel} from '@/lib/ai-models';
import {useRef,useState} from 'react';
import {CheckCircle2,ExternalLink,Eye,EyeOff,KeyRound,Loader2,Settings,ShieldCheck,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {toast} from 'sonner';
export type ConnectionSettings={careerKey:string;aiKey:string;model:AIModel;aiConsent:boolean};
export const emptySettings:ConnectionSettings={careerKey:'',aiKey:'',model:DEFAULT_AI_MODEL,aiConsent:false};
type TestState={status:'idle'|'busy'|'ok'|'error';message:string};
const idle:TestState={status:'idle',message:''};
export function ApiSettings({value,onApply,disabled=false}:{value:ConnectionSettings;onApply:(v:ConnectionSettings)=>void;disabled?:boolean}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(value),[visible,setVisible]=useState({career:false,openai:false});
 const [tests,setTests]=useState<{career:TestState;openai:TestState}>({career:idle,openai:idle});
 const generations=useRef({career:0,openai:0}),testing=useRef({career:false,openai:false});
 function openDialog(v:boolean){if(v){setDraft({...value});setTests({career:value.careerKey?{status:'ok',message:'이 화면에서 연결을 확인한 키예요.'}:idle,openai:value.aiKey?{status:'ok',message:'이 화면에서 연결을 확인한 키예요.'}:idle});setVisible({career:false,openai:false});}else{generations.current.career++;generations.current.openai++;testing.current={career:false,openai:false};setDraft(emptySettings);}setOpen(v);}
 function invalidate(provider:'career'|'openai'){generations.current[provider]++;testing.current[provider]=false;setTests(s=>({...s,[provider]:idle}));}
 async function test(provider:'career'|'openai'){
  if(testing.current[provider])return;const key=provider==='career'?draft.careerKey:draft.aiKey;
  if(key.trim().length<8){setTests(s=>({...s,[provider]:{status:'error',message:'발급받은 키를 입력해 주세요.'}}));return;}
  if(provider==='openai'&&!draft.aiConsent){toast.info('아래 교사용 AI 체험 안내를 먼저 확인해 주세요.');return;}
  testing.current[provider]=true;const gen=++generations.current[provider];setTests(s=>({...s,[provider]:{status:'busy',message:'실제 API 응답을 확인하고 있어요…'}}));
  try{const d=await api<{message:string}>('/api/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,apiKey:key.trim(),...(provider==='openai'?{model:draft.model,consent:draft.aiConsent}:{})}),signal:AbortSignal.timeout(45000)});if(gen===generations.current[provider])setTests(s=>({...s,[provider]:{status:'ok',message:d.message}}));}catch(e){if(gen===generations.current[provider])setTests(s=>({...s,[provider]:{status:'error',message:e instanceof Error?e.message:'연결에 실패했어요. 다시 확인해 주세요.'}}));}finally{if(gen===generations.current[provider])testing.current[provider]=false;}
 }
 const pending=tests.career.status==='busy'||tests.openai.status==='busy';
 const canApply=!pending&&(!draft.careerKey||tests.career.status==='ok')&&(!draft.aiKey||(tests.openai.status==='ok'&&draft.aiConsent));
 function apply(){if(!canApply)return;onApply({...draft,careerKey:draft.careerKey.trim(),aiKey:draft.aiKey.trim(),aiConsent:!!draft.aiKey&&draft.aiConsent});openDialog(false);toast.success('설정을 적용했어요. 새로고침하면 키가 지워져요.');}
 return <><button className="settings-button" disabled={disabled} onClick={()=>openDialog(true)} aria-label="API 연결 설정"><Settings size={18}/><span>설정</span>{(value.careerKey||value.aiKey)&&<span className="connected-dot"/>}</button><Dialog open={open} onOpenChange={openDialog}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle><Settings size={22}/>나만의 연결 설정</DialogTitle><DialogDescription>사용자마다 자신의 키로 연결해요. 키 없이도 상황 연습과 포트폴리오를 사용할 수 있어요.</DialogDescription></DialogHeader>
 <div className="settings-security"><ShieldCheck size={21}/><p><strong>키는 현재 화면에서만 잠시 기억해요.</strong><br/>앱의 데이터베이스·브라우저 저장소·결과지에 저장하지 않아요. 새로고침하거나 탭을 닫으면 다시 입력해야 해요.</p></div>
 {(['career','openai'] as const).map(provider=>{const isCareer=provider==='career',key=isCareer?draft.careerKey:draft.aiKey,state=tests[provider];return <section className="connection-card" key={provider}><div className="connection-heading"><span className={`connection-icon ${isCareer?'mint':'blue'}`}><KeyRound size={20}/></span><div><h3>{isCareer?'커리어넷':'OpenAI'} API</h3><p>{isCareer?'직업 · 학과 · 학교 공식 자료 검색':'자유롭게 묻고 답하는 면담 · 교사용 시험'}</p></div><span className={`badge ${state.status==='ok'?'mint':''}`}>{state.status==='ok'?'연결 확인':'선택 연결'}</span></div>
 <label className="api-label" htmlFor={'key-'+provider}>{isCareer?'커리어넷 인증 키':'OpenAI 비밀 키'}</label><div className="secret-input"><input id={'key-'+provider} type={visible[provider]?'text':'password'} value={key} autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={512} placeholder={isCareer?'승인된 커리어넷 키를 붙여넣으세요':'sk-…'} onChange={e=>{setDraft({...draft,[isCareer?'careerKey':'aiKey']:e.target.value.trim()});invalidate(provider);}}/><button className="icon-button" aria-label={visible[provider]?'키 숨기기':'키 표시하기'} onClick={()=>setVisible({...visible,[provider]:!visible[provider]})}>{visible[provider]?<EyeOff size={18}/>:<Eye size={18}/>}</button>{key&&<button className="icon-button" aria-label={isCareer?'커리어넷 키 입력 지우기':'OpenAI 키 입력 지우기'} onClick={()=>{setDraft({...draft,[isCareer?'careerKey':'aiKey']:''});invalidate(provider);}}><Trash2 size={16}/></button>}</div>
 {!isCareer&&<><div className="model-row"><label htmlFor="ai-model">대화 모델</label><Select value={draft.model} onValueChange={v=>{setDraft({...draft,model:v as ConnectionSettings['model']});invalidate('openai');}}><SelectTrigger id="ai-model"><SelectValue/></SelectTrigger><SelectContent>{AI_MODEL_IDS.map(model=><SelectItem key={model} value={model}>{AI_MODELS[model].label}</SelectItem>)}</SelectContent></Select></div><p className="tiny" role="status">{AI_MODELS[draft.model].description} 모델을 바꾸면 연결을 다시 확인해 주세요. 사용 가능 여부는 OpenAI 계정 권한에 따라 달라요. <a href="https://developers.openai.com/api/docs/pricing" target="_blank" rel="noreferrer">모델별 요금 확인</a></p><label className="check-field ai-consent"><Checkbox checked={draft.aiConsent} onCheckedChange={v=>{setDraft({...draft,aiConsent:!!v});invalidate('openai');}}/><span>성인 교사가 가상의 내용으로 시험하며, API 사용 요금과 외부 전송 안내를 확인했어요.<small>면담 질문과 최근 20개 문답이 앱 서버를 거쳐 OpenAI로 전송돼요. 학생 개인정보는 입력하지 마세요. 연결 확인에도 짧은 생성 요청 1회가 발생해요.</small></span></label></>}
 <div className="connection-actions"><a href={isCareer?'https://www.career.go.kr/cnet/front/openapi/openApiMainCenter.do':'https://platform.openai.com/api-keys'} target="_blank" rel="noreferrer">{isCareer?'키 신청·승인 확인':'API 키 발급'}<ExternalLink size={13}/></a><button className="secondary small" disabled={!key||state.status==='busy'||(!isCareer&&!draft.aiConsent)} onClick={()=>test(provider)}>{state.status==='busy'?<Loader2 size={15} className="spin"/>:state.status==='ok'?<CheckCircle2 size={15}/>:<KeyRound size={15}/>}연결 확인</button></div>{state.message&&<p className={`connection-message ${state.status}`} role="status">{state.message}</p>}{isCareer&&<p className="tiny">커리어넷 키만 연결하면 공식 자료 검색 + 미리 작성된 상황 면담을 이용해요. 합격선·내신 등급 정보가 자동으로 생기지는 않아요.</p>}</section>;})}
 <details className="settings-details"><summary>수업에 사용하기 전, 꼭 확인해 주세요</summary><p>이 메뉴의 OpenAI 연결은 선생님이 시험하는 기능이에요. 학생에게 교사의 키를 나눠 주지 마세요. 학급 사용은 접근 권한, 보호자·학교의 동의 절차, AI 제공사의 미성년자 이용 조건과 데이터 처리 설정을 확인한 뒤 별도로 준비해야 해요.</p><p>AI 응답 저장은 요청에서 끄지만, 이것만으로 서비스 제공사의 보존 정책이 모두 해제되지는 않아요. API 요금은 키 소유자의 계정에 부과되며, ChatGPT 구독과 별도예요. 이 앱은 사용자별 하루 AI 요청 100회·연결 확인 30회로 제한해요.</p><p><a href="https://developers.openai.com/api/docs/guides/safety-checks/under-18-api-guidance" target="_blank" rel="noreferrer">미성년자 보호 안내</a> · <a href="https://developers.openai.com/api/docs/guides/your-data" target="_blank" rel="noreferrer">API 데이터 처리 안내</a></p><p>앱 서버는 키를 필요한 API에만 전달하며 응답에 되돌려 주지 않아요. 커리어넷 검색어도 서비스에 전달되므로 개인정보를 적지 마세요.</p></details>
 <div className="settings-footer"><button className="text-button danger" onClick={()=>{onApply({...emptySettings});openDialog(false);toast.success('현재 화면의 모든 키 연결을 해제했어요. 면담 기록은 유지돼요.');}}><Trash2 size={15}/>모든 키 지우기</button><button className="primary" disabled={!canApply} onClick={apply}>설정 적용<CheckCircle2 size={16}/></button></div>{!canApply&&<p className="tiny">입력한 키의 연결 확인을 마치거나, 사용하지 않을 키를 비워 주세요.</p>}
 </DialogContent></Dialog></>;
}
