"use client";
import Link from "next/link";
import {useState} from 'react';
import Image from 'next/image';
import {ArrowRight,BookOpen,Eye,EyeOff,Loader2,LockKeyhole,MessageCircle,ShieldCheck} from 'lucide-react';
export function LoginForm(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function login(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');
 try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error);window.location.replace('/teacher');}
 catch(e){setError(e instanceof Error?e.message:'연결을 확인하고 다시 시도해 주세요.');setBusy(false);}}
 return <main className="login-shell"><section className="login-story"><Link className="brand" href="/"><span className="brand-icon"><MessageCircle size={23}/></span>꿈터뷰<span className="brand-dot">.</span></Link><span className="eyebrow">질문 하나로, 꿈에 한 걸음</span><h1>좋은 질문이 자라는<br/>우리의 면담 스튜디오</h1><p>궁금한 직업을 만나고, 내 생각으로 질문하고.<br/>오늘의 발견을 한 장의 꿈 이야기로 남겨요.</p><Image src="/mascot.png" alt="마이크와 노트를 든 파란 곰 꿈이" width={320} height={320} priority/><div className="login-journey"><span>01 직업 탐색</span><span>02 면담 연습</span><span>03 배움 기록</span></div></section><section className="login-card"><span className="login-lock"><LockKeyhole size={25}/></span><span className="eyebrow">TEACHER STUDIO</span><h2>선생님, 어서 오세요</h2><p className="muted">개인 서버 보관함과 API 설정을 사용하는 교사용 메뉴예요.</p><div className="login-public-links"><Link className="primary full" href="/">학생 체험 바로 시작<ArrowRight size={17}/></Link><Link className="secondary full" href="/demo">샘플로 기능 둘러보기</Link><p className="tiny">학생은 로그인이나 비밀번호가 필요 없어요.</p></div><form onSubmit={login}><div className="field"><label htmlFor="username">아이디</label><input id="username" autoComplete="username" autoCapitalize="none" spellCheck={false} required maxLength={40} value={username} onChange={e=>setUsername(e.target.value)} placeholder="교사 아이디"/></div><div className="field"><label htmlFor="password">비밀번호</label><div className="login-password"><input id="password" type={visible?'text':'password'} autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} placeholder="비밀번호를 입력해 주세요"/><button type="button" className="icon-button" aria-label={visible?'비밀번호 숨기기':'비밀번호 표시'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{error&&<p role="alert" className="error-message">{error}</p>}<button className="primary full" disabled={busy}>{busy?<Loader2 size={18} className="spin"/>:<ArrowRight size={18}/>}면담 스튜디오 들어가기</button></form><div className="login-note"><ShieldCheck size={19}/><p>선생님 전용 체험 공간이에요.<br/>면담 기록은 로그인한 계정에만 보관돼요.</p></div><p className="tiny"><BookOpen size={14}/> 계정이 없거나 비밀번호를 잊었다면 운영자에게 문의해 주세요.</p></section></main>;
}
